### ISSUE TITLE
Add different screeenshot of application.

### ISSUE THREAD

**Issue by akshyin** [shri54726/Project-E-Waiter-#7]

**Comment by darshanraut123** [comment]
![Screenshot (18)](https://user-images.githubusercontent.com/56134448/73411096-2fed7500-432a-11ea-8aa9-dc6bbe1a4590.png)
![Screenshot (19)](https://user-images.githubusercontent.com/56134448/73411097-2fed7500-432a-11ea-9bbc-f8439a693c30.png)
![Screenshot (20)](https://user-images.githubusercontent.com/56134448/73411098-30860b80-432a-11ea-8ff6-1c29c75397ae.png)
![Screenshot (21)](https://user-images.githubusercontent.com/56134448/73411099-30860b80-432a-11ea-8ba0-70817a9be1f0.png)
![Screenshot (22)](https://user-images.githubusercontent.com/56134448/73411100-30860b80-432a-11ea-8752-9328958cfcdc.png)
![Screenshot (23)](https://user-images.githubusercontent.com/56134448/73411101-311ea200-432a-11ea-911a-6d5cf447345b.png)
![Screenshot (24)](https://user-images.githubusercontent.com/56134448/73411102-311ea200-432a-11ea-93f0-eb4bf59ff45f.png)
![Screenshot (25)](https://user-images.githubusercontent.com/56134448/73411103-311ea200-432a-11ea-8595-a58f73d2c692.png)
![Screenshot (26)](https://user-images.githubusercontent.com/56134448/73411105-31b73880-432a-11ea-9985-b51ec1ebcfab.png)
![Screenshot (27)](https://user-images.githubusercontent.com/56134448/73411106-31b73880-432a-11ea-8c3e-3f56560a581d.png)
![Screenshot (8)](https://user-images.githubusercontent.com/56134448/73411108-324fcf00-432a-11ea-89f0-0ef728836714.png)
![Screenshot (9)](https://user-images.githubusercontent.com/56134448/73411110-324fcf00-432a-11ea-809c-eda759e2fc83.png)
![Screenshot (10)](https://user-images.githubusercontent.com/56134448/73411111-32e86580-432a-11ea-885f-c3f08a3f8ca8.png)
![Screenshot (11)](https://user-images.githubusercontent.com/56134448/73411112-3380fc00-432a-11ea-8add-06b48267924e.png)
![Screenshot (12)](https://user-images.githubusercontent.com/56134448/73411113-3380fc00-432a-11ea-84ca-8d02fb734cab.png)
![Screenshot (13)](https://user-images.githubusercontent.com/56134448/73411114-3380fc00-432a-11ea-9f92-33899f47552b.png)
![Screenshot (15)](https://user-images.githubusercontent.com/56134448/73411115-34199280-432a-11ea-941a-048cced185c6.png)
![Screenshot (16)](https://user-images.githubusercontent.com/56134448/73411116-34b22900-432a-11ea-91c4-f1d057a67e25.png)
![Screenshot (17)](https://user-images.githubusercontent.com/56134448/73411118-354abf80-432a-11ea-803d-6de1ae3b7fcc.png)

**Comment by darshanraut123** [comment]
Screenshots Uploaded.
